Areas/Admin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TiendaOnline.Areas.Admin.Model;
using TiendaOnline.Data;
using TiendaOnline.Data.Migrations;

namespace TiendaOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;
        UserManager<IdentityUser> userManager;
        
        ApplicationDbContext _db;

        //public UserManager<IdentityRole> User { get; }

        public RoleController(RoleManager<IdentityRole> _roleManager, ApplicationDbContext db, UserManager<IdentityUser> _userManager)
        {
            roleManager = _roleManager;
            _db = db;
            userManager = _userManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            ViewBag.Roles = roles;
            return View();
        }

        public async Task<IActionResult>create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> create(string name)
        {

            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await roleManager.RoleExistsAsync(role.Name);
            if(isExist)
            {
                ViewBag.mgs = "Este nombre de rol ya existe";
                ViewBag.name = name;
                return View();
            }
            var result = await roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "El rol ha sido guardado exitosamente";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }


        public async Task<IActionResult> Edit(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if(role== null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string name)
        {

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "Este nombre de rol ya existe";
                ViewBag.name = name;
                return View();
            }
            var result = await roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "El rol ha sido modificado correctamente";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            var result = await roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "El rol ha sido eliminado correctamente";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Assign()
        {
            ViewData["UserId"] = new SelectList(_db.user.Where(f=>f.LockoutEnd<DateTime.Now|| f.LockoutEnd==null).ToList(), "Id", "UserName") ;
            ViewData["RoleId"] = new SelectList(roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(RoleUservm vm)
        {
            var user = _db.user.FirstOrDefault(c => c.Id == vm.UserId);
            var checking = await userManager.IsInRoleAsync(user, vm.RoleId);
            if (checking)
            {
                ViewBag.msg = "Este Usuario ya tiene asignado este rol";
                ViewData["UserId"] = new SelectList(_db.user.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
                ViewData["RoleId"] = new SelectList(roleManager.Roles.ToList(), "Name", "Name");
                return View();
            }



             var role = await userManager.AddToRoleAsync(user, vm.RoleId);
            if (role.Succeeded)
            {
                TempData["Save"] = "El rol ha sido asignado correctamente";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public ActionResult AssignUserRole()
        {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join a in _db.user on ur.UserId equals a.Id

                         select new UserRoleMaping()
                         {
                             UserId = ur.UserId,
                             RoleId = ur.RoleId,
                             UserName = a.UserName,
                             RoleName = r.Name
                         };

            ViewBag.UserRole = result;

            return View();
        }
    }
}

Areas/Customer/Controllers/OrdenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TiendaOnline.Data;
using TiendaOnline.Models;
using TiendaOnline.utility;

namespace TiendaOnline.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class OrdenController : Controller
    {
        public ApplicationDbContext db;
        SignInManager<IdentityUser> SignInManager;
        

        public OrdenController(ApplicationDbContext _db, SignInManager<IdentityUser> _SignInManager)
        {
            db = _db;
            SignInManager = _SignInManager;
        }
        [Authorize]
        public IActionResult VerOrdenes()
        {

            if (SignInManager.IsSignedIn(User)) { 
               
            string email = User.Identity.Name;
            return View(db.Orden.Where(c => c.Email == email).ToList());
            }
            return View();
            
        }
        [Authorize]
        public IActionResult Pago()
        {

            return View(db.Carrito.Include(c=>c.Producto).Where(c=>c.email==User.Identity.Name).ToList());
        }
        [Authorize]
        public IActionResult CheckOut()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckOut(Orden or)
        {
                        
            or.Email = User.Identity.Name;
          
             or.NoOrder = GetOrdenNo();
            or.Estado = "En proceso";
            db.Orden.Add(or);
            await db.SaveChangesAsync();
         

            return RedirectToAction(nameof(Pago));
        }

        public string GetOrdenNo()
        {
            int rowCount = db.Orden.ToList().Count();
            return rowCount.ToString("000");
        }
        public IActionResult Index()
        {
            return View(db.Orden.ToList());
        }

        public IActionResult Edit(int? id)
        {
          
            if (id == null)
            {
                return NotFound();

            }
            var ord = db.Orden.Find(id);
            if (ord == null)
            {
                return NotFound();
            }
            return View(ord);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(Orden ordenes)
        {
            if (ModelState.IsValid)
            {
                db.Update(ordenes);
                await db.SaveChangesAsync();
                TempData["editar"] = "La orden se actualizó correctamente!";
                return RedirectToAction(nameof(Index));
            }
            return View(ordenes);
        }

        [HttpGet]
       public IActionResult Mapas()
        {
            return View(db.Orden.ToList());
        }


        [HttpPost]
        public IActionResult Mapas(string estado)
        {
            ViewData["Estado"] = estado;
            return View(db.Orden.ToList());
        }

    }


}

Areas/Customer/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TiendaOnline.Data;
using TiendaOnline.Models;

namespace TiendaOnline.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class UserController : Controller
    {
        UserManager<IdentityUser> userManager;
        ApplicationDbContext db;
        public UserController(UserManager<IdentityUser> _userManager, ApplicationDbContext _db)
        {
           userManager = _userManager;
            db = _db;
        }

        public IActionResult Index()
        {
            return View(db.user.ToList());
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ApplicationUser user)
        {
           
            if (ModelState.IsValid) {
                user.UserName = user.Email;
                var result = await userManager.CreateAsync(user, user.PasswordHash);
                if (result.Succeeded)
                {
                    TempData["Save"] = "Usuario registrado correctamente";
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
           
            
            return View();
        }
        public async Task<IActionResult> Edit(string id)
        {
            var user = db.user.FirstOrDefault(c => c.Id == id);
            if (user == null)
            {
                return NotFound();

            }
          
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            var userInfo = db.user.FirstOrDefault(c => c.Id == user.Id);
            if (userInfo == null)
            {
                return NotFound();

            }
            userInfo.Nombre = user.Nombre;
            userInfo.Apellido = user.Apellido;
            userInfo.datebirth = user.datebirth;
            userInfo.Email = user.UserName;

            var result = await userManager.UpdateAsync(userInfo);
            if (result.Succeeded)
            {

                TempData["Save"] = "Usuario editado correctamente";
                return RedirectToAction(nameof(Index));
            }
            return View(userInfo);
        }
        public async Task<IActionResult> Detail(string id)
        {
            var user = db.user.FirstOrDefault(c => c.Id == id);
            if (user == null)
            {
                return NotFound();

            }

            return View(user);
        }
        public async Task<IActionResult> Bloquear(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = db.user.FirstOrDefault(c => c.Id == id);
            if (user == null)
            {
                return NotFound();

            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Bloquear(ApplicationUser user)
        {
            var userInfo = db.user.FirstOrDefault(c => c.Id == user.Id);
            if (userInfo == null)
            {
                return NotFound();

            }
            userInfo.LockoutEnd = DateTime.Now.AddYears(100);
            int rowAf = db.SaveChanges();
            if (rowAf > 0)
            {
                TempData["Save"] = "Usuario Bloqueado exitosamente";
                return RedirectToAction(nameof(Index));
            }
           
           
            return View(userInfo);
        }

        public async Task<IActionResult> Active(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = db.user.FirstOrDefault(c => c.Id == id);
            if (user == null)
            {
                return NotFound();

            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Active(ApplicationUser user)
        {
            var userInfo = db.user.FirstOrDefault(c => c.Id == user.Id);
            if (userInfo == null)
            {
                return NotFound();

            }
            userInfo.LockoutEnd = DateTime.Now.AddDays(-1);
            int rowAf = db.SaveChanges();
            if (rowAf > 0)
            {
                TempData["Save"] = "Usuario Habilitado exitosamente";
                return RedirectToAction(nameof(Index));
            }


            return View(userInfo);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = db.user.FirstOrDefault(c => c.Id == id);
            if (user == null)
            {
                return NotFound();

            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ApplicationUser user)
        {
            var userInfo = db.user.FirstOrDefault(c => c.Id == user.Id);
            if (userInfo == null)
            {
                return NotFound();

            }
            db.user.Remove(userInfo);
            int rowAf = db.SaveChanges();
            if (rowAf > 0)
            {
                TempData["Save"] = "Usuario eliminado exitosamente";
                return RedirectToAction(nameof(Index));
            }


            return View(userInfo);
        }
    }
}

Views/Shared/_ButtonPartial.cshtml
@model int  
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td>
    <div class="btn-group ">

        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-outline-primary" asp-route-id="@Model">
            <span class="glyphicon glyphicon-edit"></span> Editar
        </a>

        <a asp-action="Details" asp-controller="ProductTypes" class="btn btn-outline-success" asp-route-id="@Model">
            <span class="glyphicon glyphicon-list-alt"></span> Detalles
        </a>



        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-outline-danger" asp-route-id="@Model">
            <span class="glyphicon glyphicon-trash"></span> Borrar
        </a>
        
    </div>
</td>

Views/Shared/_ButtonPartial2.cshtml
@model int  
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td>
    <div class="btn-group ">

        <a asp-action="Edit" asp-controller="" class="btn btn-outline-primary" asp-route-id="@Model">
            <span class="glyphicon glyphicon-edit"></span> Editar
        </a>

        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-outline-success" asp-route-id="@Model">
            <span class="glyphicon glyphicon-list-alt"></span> Detalles
        </a>



        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-outline-danger" asp-route-id="@Model">
            <span class="glyphicon glyphicon-trash"></span> Borrar
        </a>

        @*<a asp-action="Edit" asp-controller="SpecialTag" class="btn btn-outline-primary" asp-route-id="@Model">Editar</a>
        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-outline-success" asp-route-id="@Model">Detalles</a>
        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-outline-danger" asp-route-id="@Model">Borrar</a>*@
    </div>
</td>

Views/Shared/_ButtonPartial3.cshtml
@model int  
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td>
    <div class="btn-group ">
        <a asp-action="Edit" asp-controller="Producto" class="btn btn-outline-primary" asp-route-id="@Model">
            <span class="glyphicon glyphicon-edit"></span> Editar
        </a>

        <a asp-action="Details" asp-controller="Producto" class="btn btn-outline-success" asp-route-id="@Model">
            <span class="glyphicon glyphicon-list-alt"></span> Detalles
        </a>

        

        <a asp-action="Delete" asp-controller="Producto" class="btn btn-outline-danger" asp-route-id="@Model">
            <span class="glyphicon glyphicon-trash"></span> Borrar
        </a>


    </div>
</td>

Views/Shared/_ButtonPartial4.cshtml
@model int  
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td>
    <div class="btn-group ">
        

        <a asp-action="Edit" asp-controller="Orden" class="btn btn-outline-primary" asp-route-id="@Model">
            <span class="glyphicon glyphicon-edit"></span> Editar
        </a>
    </div>
</td>

Views/Shared/_ButtonPartial5.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <td>
        <div class="btn-group ">
            <a asp-action="Edit" asp-controller="User" class="btn btn-outline-primary" asp-route-id="@Model">
                <span class="glyphicon glyphicon-edit"></span> Editar
            </a>

            <a asp-action="Details" asp-controller="User" class="btn btn-outline-success" asp-route-id="@Model">
                <span class="glyphicon glyphicon-list-alt"></span> Detalles
            </a>

            <a asp-action="Details" asp-controller="User" class="btn btn-outline-dark" asp-route-id="@Model">
                <span class="glyphicon glyphicon-ban-circle"></span> Bloquear
            </a>



            <a asp-action="Delete" asp-controller="User" class="btn btn-outline-danger" asp-route-id="@Model">
                <span class="glyphicon glyphicon-trash"></span> Borrar
            </a>


            @*<a asp-action="Edit" asp-controller="User" class="btn btn-outline-primary" asp-route-id="@Model">Editar</a>
        <a asp-action="Detail" asp-controller="User" class="btn btn-outline-success" asp-route-id="@Model">Detalles</a>
        <a asp-action="Bloquear" asp-controller="User" class="btn btn-outline-info" asp-route-id="@Model">Bloquear</a>
        <a asp-action="Delete" asp-controller="User" class="btn btn-outline-danger" asp-route-id="@Model">Borrar</a>*@
        </div>
    </td>

Views/Shared/_ButtonPartial6.cshtml
@model string 
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td>
    <div class="btn-group ">
        <a asp-action="Edit" asp-controller="Role" class="btn btn-outline-primary" asp-route-id="@Model">
            <span class="glyphicon glyphicon-edit"></span> Editar
        </a>

        <a asp-action="Details" asp-controller="Role" class="btn btn-outline-success" asp-route-id="@Model">
            <span class="glyphicon glyphicon-list-alt"></span> Detalles
        </a>



        <a asp-action="Delete" asp-controller="Role" class="btn btn-outline-danger" asp-route-id="@Model">
            <span class="glyphicon glyphicon-trash"></span> Borrar
        </a>
    </div>
</td>