Areas/Admin/Controllers/ClientesGestorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TiendaOnline.Data;
using TiendaOnline.Models;

namespace TiendaOnline.Areas.Customer.Controllers
{
    [Area("Admin")]
    public class ClientesGestorController : Controller
    {
        UserManager<IdentityUser> userManager;
        ApplicationDbContext db;
        public ClientesGestorController(UserManager<IdentityUser> _userManager, ApplicationDbContext _db)
        {
           userManager = _userManager;
            db = _db;
        }

        public IActionResult Index()
        {
           
            return View(db.user.ToList());
           

        }

        public async Task<IActionResult> VerCompras(string id)
        {
            var user = db.user.FirstOrDefault(c => c.Id == id);

            var product = db.Carrito.Include(c => c.Producto).Where(c => c.email == user.UserName).ToList();
            return View(product);
        }
      
    }
}

Areas/Admin/Views/ClientesGestor/Index.cshtml
@model IEnumerable<TiendaOnline.Models.ApplicationUser>
@{
    ViewData["Title"] = "Index";
}

<br />
<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-info">Lista de Clientes</h2>
    </div>
   
</div>
<br />

<div>
    <table class="table table-striped border">

        <tr class="table-info text-center">
            <th>Nombre</th>
            <th>Nombre de Usuario</th>
 
            <th></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
    <tr>
        <td>@item.Nombre @item.Apellido</td>
        <td>@item.UserName</td>

        

        <td style="width: 150px">

            <a asp-action="VerCompras" class="btn btn-info" asp-route-id="@item.Id">
                <span class="glyphicon glyphicon-eye-open"></span> Ver Compras
            </a>
            @*<a asp-action="VerCompras" class="btn btn-info" asp-route-id="@item.Id">
            Ver Compras
            <i class="far fa-trash-alt"></i>
        </a>*@
        </td>


    </tr>
        }
    </table>
</div>

@section scripts{
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/alertify.min.js"></script>
    <script type="text/javascript">
    $(function () {
        var save = '@TempData["Save"]'

        if (save != null) {
            alertify.success(save);

        }
    });
    </script>

}

Areas/Admin/Views/ClientesGestor/VerCompras.cshtml
@using TiendaOnline.Models
@model List<Carrito>
@{
    ViewData["Title"] = "Cart";
}

<h1>Compras del Cliente</h1>


<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Imagen </th>
                <th>Nombre </th>
                <th>Cantidad</th>
                <th>Precio</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="~/@item.Producto.image" width="200" height="150" />
                    </td>
                    <td>@item.Producto.Name</td>
                    <td>@item.Cantidad</td>
                    <td>@item.Producto.Price  </td>

                   
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="row">
    @*<div class="col-6">
        <a asp-action="Index" asp-controller="Home" class="btn btn-success">Volver al principio</a>
    </div>*@
    <div class="col-6 text-right">
        <h3>Cantidad Total</h3>
        <h3>Total Cuenta: @Model.Sum(c => c.Producto.Price)</h3>
        <a asp-area="Admin" asp-action="Index" asp-controller="ClientesGestor" class="btn btn-info">Volver a Lista de Clientes</a>
       

</div>

</div>