Areas/Admin/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TiendaOnline.Data;
using TiendaOnline.Models;
using TiendaOnline.utility;

namespace TiendaOnline.Areas.Admin.Controllers
{[Area("Admin")]
    public class CategoriasController : Controller
    {
        private ApplicationDbContext _db;

        public CategoriasController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Comida()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c=>c.ProductTypes.ProductType=="Comida").ToList());
        }

        public IActionResult Electronica()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Electronica").ToList());
        }

        public IActionResult Ropas()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Ropas").ToList());
        }
        public IActionResult Deportes()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Deportes").ToList());
        }
        public IActionResult VideoJuegos()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Video Juegos").ToList());
        }
        public IActionResult Salud()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Salud").ToList());
        }
        public IActionResult CuidadoPersonal()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Cuidado Personal").ToList());
        }
        public IActionResult Calzados()
        {
            return View(_db.Productos.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.ProductTypes.ProductType == "Calzados").ToList());
        }



        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Productos.Include(c => c.ProductTypes).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();

            }
            return View(product);
        }
        [Authorize]
        [HttpPost]
        [ActionName("Details")]
        public async Task<ActionResult> ProductDetails(int? id)
        {
            Carrito cr = new Carrito();
            List<Producto> producto = _db.Productos.Include(c => c.ProductTypes).Where(c => c.Id == id).ToList();
            //var cartItem = _db.Carrito.SingleOrDefault(c => c.email == User.Identity.Name && c.ProductId == id);

            if (producto != null)
            {
                foreach (var prod in producto)
                {
                    cr.ProductId = prod.Id;
                }
            }
           
                cr.email = User.Identity.Name;
            
            cr.Cantidad = 1;

            await _db.Carrito.AddAsync(cr);

            _db.SaveChanges();

            return View();
        }
    }
}

Areas/Admin/Views/Categorias/Calzados.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Calzados";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/Comida.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Comida";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/CuidadoPersonal.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Cuidado Personal";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/Deportes.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Deportes";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/Details.cshtml
@model TiendaOnline.Models.Producto
@{
    ViewData["Title"] = "Detalles";
}
@using TiendaOnline.utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{

    List<Producto> productos = HttpContextAccessor.HttpContext.Session.Get<List<Producto>>("producto");
    Producto product = null;
    if (productos != null)
    {
        product = productos.FirstOrDefault(c => c.Id == Model.Id);
    }

}




<br />
<h2 class="text-info">Detalles de Producto</h2>
<form asp-action="Details" method="post" enctype="multipart/form-data">
    <div class="p-4 rounded border row">
        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name">Nombre: </label>
                </div>
                <div class="col-8">
                    <input type="hidden" asp-for="Id" />
                    <input asp-for="Name" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price">Precio: </label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Descripcion">Descripcion: </label>
                </div>
                <div class="col-8">
                    <input asp-for="Descripcion" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            @*<div class="form-group row">
                    <div class="col-4">
                        <label asp-for="image">Foto: </label>
                    </div>
                    <div class="col-8">
                        <input asp-for="image" class="form-control" type="file" />
                    </div>
                    <span asp-validation-for="image" class="text-danger"></span>
                </div>*@
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Color">Color: </label>
                </div>
                <div class="col-8">
                    <input asp-for="Color" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Cantidad">Cantidad: </label>
                </div>
                <div class="col-8">
                    <input asp-for="Cantidad" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>


            <div class="form-group row">
                <div class="col-4">

                </div>
                <div class="col-8">
                    @if (product != null)
                    {
                        <button type="submit" class="btn btn-danger form-control" asp-action="Remove" asp-route-id="@Model.Id">Quitar del Carrito</button>
                    }
                    <input type="submit" class="btn btn-info form-control" value="Agregar al carrito" />
                </div>

            </div>
        </div>
        <div class="col-1">
        </div>
        @*<div class="col-3">
                <img src="~/@Model.image" width="100%" style="border-radius: 5px; border: 1px solid #efefef" />
            </div>*@

        <div class="form-group">

            <a asp-action="Index" class="btn btn-success">Ir a la lista</a>
        </div>
    </div>
</form>
@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/Categorias/Electronica.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Electronica";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/Ropas.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Ropas";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/Salud.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Salud";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

Areas/Admin/Views/Categorias/VideoJuegos.cshtml
@using TiendaOnline.Models
@model List<Producto>
@{
    ViewData["Title"] = "Video Juegos";
}
<br />
<br />


<div class="row">
    @foreach (var produc in Model)
    {

        <div class="col-4">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color:black">@produc.Name</label>
                    </h4>
                </div>
                <img src="/@produc.image" alt="Card Image" class="card-img-top" style="height:250px; width:250px" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:15px" ; color="#a51313"><b>Precio: @produc.Price</b></label>
                        </div>
                        <a asp-action="Details" asp-controller="Categorias" asp-route-id="@produc.Id" class="btn btn-info form-control btn-sm align-text-top" style="font-size:15px ;color:black">Detalles</a>
                    </div>
                </div>
            </div>

        </div>
    }
</div>